############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  username-to-lowercase:
    runs-on: ubuntu-latest
    outputs:
      LOWERCASE_USERNAME: ${{ steps.set-lowercase.outputs.LOWERCASE_USERNAME }}
    steps:
      - name: Set username to lowercase
        id: set-lowercase
        run: echo "::set-output name=LOWERCASE_USERNAME::$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')"

  build-push-frontend:
    needs: [username-to-lowercase]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }} --password-stdin
      - name: Build/Push Frontend Docker Image
        run: |
          docker build --push -t ghcr.io/${{ needs.username-to-lowercase.outputs.LOWERCASE_USERNAME }}/k10s-frontend:latest ./App/Frontend